Disable auto topic creation
cloud-green/kafka-snap-charm pull request #17
Opened 2019-04-09 08:09 UTC by kngu9

We don't want to auto create topics if they don't exist.

2019-04-09 14:35 UTC, alesstimec approved these changes
LGTM with a nitpick

2019-04-09 14:35 UTC, alesstimec commented on charm/kafka/templates/server.properties
> +# NOTE: If we want to expose Kafka pubically, this has to be a public address or else Kafka will send the private ip address instead.
s/publically/publicly/

2019-04-09 14:40 UTC, cmars reviewed
Looks good, but per IRC chat, lets also:
- Add a charm config option to allow setting this to true. I think false is a sensible default though; prevents topics from getting created during a deployment before partitioning and replication have been explicitly set up.
- Manually QA test this with jmx-exporter and prometheus; confirm that the producer errors can be detected with our instrumentation. Just want to be sure we can detect and resolve a misconfiguration in production.

2019-04-09 14:44 UTC, cmars requested changes

2019-04-09 14:44 UTC, cmars commented on charm/bundle.yaml
> +    charm: /Users/khanh/Projects/jmx-exporter/builds/jmx-exporter
This won't work for anyone else. Please use a charmstore URL.

2019-04-09 14:44 UTC, cmars commented on charm/kafka/config.yaml
> +  allow_topic_creation:
Let's use the same language as the kafka config. `auto_create_topics` will be most familiar to kafka operators.

2019-04-17 13:45 UTC, cmars commented
@kngu9 This still needs fixing. I _think_ Kafka Streams creates the aggregate topics explicitly, so this is still a reasonable config option worth landing. The example bundle charm reference just needs fixing.

2019-04-17 16:22 UTC, cmars approved these changes
LGTM

2019-04-17 16:22 UTC, cmars commented on charm/kafka/templates/server.properties
> +# NOTE: If we want to expose Kafka publicly, this has to be a public address or else Kafka will send the private ip address instead.
We don't want to expose Kafka publicly.

2019-04-17 16:26 UTC, merged